### ISSUE TITLE
practica final 7

### ISSUE THREAD

**Issue by Yareli-Perez** [SistemasTecTlaxiaco/practica-final-de-hilos-topicos4yan#2]
[Practica 7.pdf](https://github.com/SistemasTecTlaxiaco/practica-final-de-hilos-topicos4yan/files/8545879/Practica.7.pdf)

**Comment by SANDRAVELASCO** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
